--sczsq31.co.santa-cruz.ca.us
DECLARE @CurrFY AS INT

SET @CurrFY = 
	CASE	
		WHEN MONTH(GETDATE()) > 6 THEN YEAR(GETDATE())+1
		ELSE YEAR(GETDATE())
	END

;

WITH X AS
	(SELECT 
		[ChkStmtDetail_Archive].[EmpNo]
		,CASE	
			WHEN MONTH([PayDate]) > 6 THEN YEAR([PayDate]) + 1
			ELSE YEAR([PayDate])
		END AS FY
		,[EmpCur]
		,[CoCur]
		,CASE WHEN [CHkDesc] IN ('REGULAR', 'OVERTIME STRAIGHT', 'OVERTIME PREMIUM', 'HOLIDAY NOT WORKED', 'ADM LEAVE TAKEN-COUNTY', 'BEREAVEMENT LEAVE', 'COMP TAKEN', 'COMP TAKEN - FMLA',
								'DIFFERENTIALS ON OT', 'IN LIEU OF MEDICAL COVERAGE', 'JURY DUTY', 'LEAVE WITH PAY', 'LONGEVITY DIFF', 'LONGEVITY DIFF 20YR', 'MID MGMT SIGNING BONUS 2017',
								'ON-CALL', 'ON-CALL - MID MGT', 'SHIFT DIFF MGT', 'SHIFT DIFF-SWING-GEN', 'SHIFT DIFF-GRAVE-GEN', 'SHIFT ON OVERTIME', 'SICK', 'SICK - FMLA', 
								'SPEC ASSIGNMENT - 5%', 'VACATION', 'VACATION - FMLA', 'VACATION - TIMEBANK', 'CALL BACK PAY', 'IN LIEU HOLIDAY-N/A OT PAY')
			THEN ([EmpCur]) 
			ELSE 0
		END AS 'Salary'

		,CASE WHEN [CHkDesc] IN ('DEFERRED COMP', 'RETIREMENT - CO SHR ACCR LIAB', 'ReTIREMENT-CO SHR', 'ROTH 457 - AFTER TAX FIXED AMT', 'ROTH 457 - AFTER TAX PERCENT A')
			THEN ([CoCur]) 
			ELSE 0
		END AS 'PERS'

		,CASE WHEN [ChkDesc] IN ('FHA ANTHEM TRAD E2 OTHER', 'CH LIFE 10K 0-25', 'CH LIFE 5K 0-25', 'CIGNA DENTAL', 'DELTA CARE DENTAL', 'DELTA DENTAL BASIC', 'DPO+ DELTA DENTAL', 
								'DPO+ DELTA DENTAL - FHA', 'EE LIFE 125K 30-34', 'EE LIFE 125K 35-39', 'EE LIFE 125K 40-44', 'EE LIFE 125K 45-49', 'EE LIFE 125K 50-54', 'EE LIFE 125K 55-59',
								'EE LIFE 125K 60-64', 'EE LIFE 175K 35-39', 'EE LIFE 175K 40-44', 'EE LIFE 200K 30-34', 'EE LIFE 25K 35-39', 'EE LIFE 25K 40-44', 'EE LIFE 25K 45-49',
								'EE LIFE 25K 50-54', 'EE LIFE 25K 55-59', 'EE LIFE 300K 45-49', 'EE LIFE 50K 60-64', 'EE LIFE 50K 65-69', 'EE LIFE 75K 45-49', 'EE LIFE 75K 50-54', 
								'EE LIFE 75K 55-59', 'EE LIFE 75K 60-64', 'FHA A SELECT EE2 MID MGT', 'FHA A TRADITIONAL  EE  DA INSP', 'FHA ANTHEM SELECT E1 OTHER', 'FHA ANTHEM SELECT E2 OTHER', 
								'FHA ANTHEM SELECT EE OTHER', 'FHA ANTHEM TRAD E1 OTHER', 'FHA ANTHEM TRAD EE OTHER', 'FHA BS ACCESS+ E1 OTHER', 'FHA BS ACCESS+ E2 OTHER', 'FHA BS ACCESS+ EE OTHER',
								'FHA DEPENDENT VISION', 'FHA DPO+ DENTAL', 'FHA HEALTH NET E1 OTHER', 'FHA HEALTH NET E2 OTHER', 'FHA HEALTH NET EE OTHER', 'FHA HN SMARTCARE E2 OTHER',
								'FHA HNSMARTCARE EE2 MID MGT', 'FHA KAISER E1 OTHER', 'FHA KAISER E2 OTHER', 'FHA KAISER EE MID MGT', 'FHA KAISER EE OTHER', 'FHA NVALUE E1 OTHER', 
								'FHA NVALUE EE OTHER', 'FHA PCARE E1 OTHER', 'FHA PCARE E2 OTHER', 'FHA PCARE EE OTHER', 'FHA PCHOICE E1 OTHER', 'FHA PCHOICE E2 OTHER', 'FHA PCHOICE EE OTHER', 
								'FHA PCHOICE EE1 MID MGT', 'FHA PCHOICE EE2 MID MGT', 'FHA PSELECT E1 OTHER', 'FHA PSELECT E2 OTHER', 'FHA PSELECT EE OTHER', 'FHA UNITED HC E1 OTHER','LIFE - $100,000',
								'LIFE - $20,000', 'LIFE - $50,000', 'MED A TRADITIONAL EE DA INSP', 'MED ANTHEM SELECT E1 OTHER', 'MED ANTHEM SELECT E2 OTHER', 'MED ANTHEM SELECT EE OTHER', 
								'MED ANTHEM TRAD EE OTHER', 'MED BS ACCESS+ E1 OTHER', 'MED BS ACCESS+ E2 OTHER', 'MED BS ACCESS+ EE OTHER', 'MED HEALTH NET E1 OTHER', 'MED HEALTH NET E2 OTHER', 
								'MED HEALTH NET EE OTHER', 'MED HN SMARTCARE E2 OTHER', 'MED HNSMARTCARE EE2 MID MGT', 'MED KAISER EE MID MGT', 'MED KAISER EE OTHER', 'MED NVALUE E1 OTHER', 
								'MED NVALUE EE OTHER', 'MED PCHOICE E1 OTHER', 'MED PCHOICE E2 OTHER', 'MED PCHOICE EE OTHER', 'MED PSELECT E1 OTHER', 'MED UNITED HC E1 OTHER', 
								'MED/H A SELECT EE2 MID MGT', 'MED/H ANTHEM SELECT E1 OTHER', 'MED/H ANTHEM SELECT E2 OTHER', 'MED/H ANTHEM SELECT EE OTHER', 'MED/H ANTHEM TRAD E1 OTHER',
								'MED/H ANTHEM TRAD E2 OTHER', 'MED/H ANTHEM TRAD EE OTHER', 'MED/H BS ACCESS+E1 OTHER', 'MED/H BS ACCESS+E2 OTHER', 'MED/H BS ACCESS+EE OTHER', 
								'MED/H HEALTH NET E1 OTHER', 'MED/H HEALTH NET E2 OTHER', 'MED/H HEALTH NET EE OTHER', 'MED/H HN SMARTCARE E2 OTHER', 'MED/H KAISER E1 OTHER', 'MED/H KAISER E2 OTHER',
								'MED/H KAISER EE OTHER', 'MED/H NVALUE E1 OTHER', 'MED/H PCARE E1 OTHER', 'MED/H PCARE E2 OTHER', 'MED/H PCARE EE OTHER', 'MED/H PCHOICE E2 OTHER',
								'MED/H PCHOICE EE OTHER', 'MED/H PCHOICE EE1 MID MGT', 'MED/H PCHOICE EE2 MID MGT', 'MED/H PSELECT E1 OTHER', 'MED/H PSELECT E2 OTHER', 'MED/H PSELECT EE OTHER',
								'MED/H UNITED HC E1 OTHER', 'PERS LTC', 'SDI', 'SP LIFE 20K 30-34', 'SP LIFE 20K 40-44', 'SP LIFE 20K 45-49', 'SP LIFE 20K 50-54', 'SP LIFE 20K 55-59', 
								'SP LIFE 20K 60-64', 'SP LIFE 20K 65-69', 'VISION', 'VISION EMP&DEP', 'LTD MGT/DA', 'LTD MGT/DA/PHY')
			THEN ([CoCur]) 
			ELSE 0
		END AS 'Ins'

		,CASE WHEN ChkDesc IN ('FICA TAX') 
			THEN ([CoCur])
			ELSE 0
		END AS 'FICA'

		,CASE WHEN ChkDesc IN ('COMP TIME PAYOFF', 'ADMIN LEAVE PAYOFF-SEP CK') 
			THEN ([EmpCur])
			ELSE 0
		END AS 'PayOuts'	

	FROM [Payroll2].[dbo].[ChkStmtDetail_Archive]

	LEFT JOIN [Payroll2].[dbo].[EmpKey] employee 
	ON employee.EmpNo = [ChkStmtDetail_Archive].EmpNo 

	WHERE 
		LEFT(Employee.EmpIndex,2) IN ('42','43')  
		AND [DataGroup] not in('10','40','60','70')
		--AND [ChkStmtDetail_Archive].EmpNo = '013636'
	)

,

Y AS 
	(SELECT 
		EmpNo
		,FY
		,SUM(Salary) AS Salary
		,SUM(FICA) AS FICA
		,SUM(PERS) AS PERS
		,SUM(Ins) AS Ins
		,SUM(Payouts) AS Payouts

	  FROM X

	  WHERE FY BETWEEN (@CurrFY - 12) AND (@CurrFY - 2)

	GROUP BY
		EmpNo
		,FY

	)

,

StdDevSet AS
	(SELECT
		EmpNo
		,AVG(Salary) OVER (PARTITION BY EmpNo) AS ybarSal
		,AVG(FICA) OVER (PARTITION BY EmpNo) AS ybarFICA
		,AVG(PERS) OVER (PARTITION BY EmpNo) AS ybarPERS
		,AVG(Ins) OVER (PARTITION BY EmpNo) AS ybarIns
		,Salary AS ySal
		,FICA AS yFICA
		,PERS AS yPERS
		,Ins AS yIns
		,AVG(FY) OVER (PARTITION BY EmpNo) AS xbar
		,FY AS x
	FROM Y
	
	WHERE FY != @CURRFY
	
	GROUP BY EmpNo, Salary, FICA, PERS, Ins, FY)

,

PrepB AS
	(SELECT
		EmpNo
		,SUM((x - xbar) * (ySal - ybarSal)) OVER (PARTITION BY Empno) AS B1SalN 
		,SUM((x - xbar) * (yFICA - ybarFICA)) OVER (PARTITION BY Empno) AS B1FicaN
		,SUM((x - xbar) * (yPERS - ybarPERS)) OVER (PARTITION BY Empno) AS B1PersN
		,SUM((x - xbar) * (yIns - ybarIns)) OVER (PARTITION BY Empno) AS B1InsN
		,SUM((x - xbar) * (x - xbar)) OVER (PARTITION BY Empno) AS B1D	
	FROM StdDevSet
	GROUP BY EmpNo, x, ySal, yFICA, yPERS, yIns, xbar, YbarSal, YbarFICA, YbarPERS, YbarIns
	)

,

CalB AS
	(SELECT
		PrepB.EmpNo
		,CASE 
			WHEN (B1D = 0 OR B1SalN <1)
			THEN 0.01 * ySal
			ELSE B1Saln/B1D
		END AS bSal
		,CASE 
			WHEN (B1D = 0 OR B1FicaN <1)
			THEN 0.01 * yFICA
			ELSE B1FicaN/B1D
		END AS bFICA
		,CASE 
			WHEN (B1D = 0 OR B1PersN <1)
			THEN 0.01 * yPERS
			ELSE B1PersN/B1D
		END AS bPERS
		,CASE 
			WHEN (B1D = 0 OR B1InsN <1)
			THEN 0.01 * yIns
			ELSE B1InsN/B1D
		END AS bIns
	FROM PrepB

	LEFT JOIN StdDevSet
		ON StdDevSet.EmpNo = PrepB.EmpNo
		AND StdDevSet.x = @CurrFY-2

	GROUP BY PrepB.EmpNo, ySal, yFICA, yPERS, yIns, B1Saln, B1FicaN, B1PersN, B1InsN, B1D

	)

--,

--StdDevY2 AS
--	(SELECT
--		StdDevY1.EmpNo
--		,ROUND(yDiffSal,0)^2 AS Col2
--		,n
--	FROM StdDevY1
--	INNER JOIN StdDevX ON StdDevX.EmpNo = StdDevY1.EmpNo
--	GROUP BY StdDevY1.EmpNo, yDiffSal)

----,

----StdDevR AS
----	(SELECT
----		EmpNo
----		,(SUM(x * ySal))/SQRT(SUM(x^2)*SUM(ySal^2)) AS rSal
----		,COUNT(x) AS n
----	FROM CalcSet
----	GROUP BY EmpNo
----	)

SELECT
--	EmpNo
--	--,rSal*Sy/
--	,Sx
*
--FROM StdDEv

FROM CalB

LEFT JOIN StdDevSet 
	ON StdDevSet.EmpNo = CalB.EmpNo

GROUP BY StdDevSet.EmpNo
	,CalB.EmpNo
	,CalB.bSal
	,CalB.bFICA
	,CalB.bPERS
	,CalB.bIns
	,ybarsal
	,ybarFICA
	,YbarPERS
	,ybarIns
	,ySal
	,yFICA
	,yPERS
	,yIns
	,xbar
	,x

ORDER BY StdDevSet.EmpNo, x

